version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/libre-asi" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" # See documentation fo  possible values
    directory: "/api" # Location of package manifests
    schedule:
       interval: "weekly"
