CREATE DATABASE libre_asi;
CREATE USER libre_asi WITH ENCRYPTED PASSWORD 'libre_asi';
GRANT ALL PRIVILEGES ON DATABASE libre_asi TO libre_asi;
\c libre_asi;
GRANT ALL ON ALL TABLES IN SCHEMA PUBLIC TO libre_asi;
GRANT ALL ON SCHEMA PUBLIC TO libre_asi;
