// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	welcome: {
		/**
		 * W​e​l​c​o​m​e​ ​t​o​ ​L​i​b​r​e​-​A​S​I
		 */
		TITLE: string
		/**
		 * L​i​b​r​e​-​A​S​I​ ​i​s​ ​a​ ​s​o​f​t​w​a​r​e​ ​t​o​o​l​ ​t​o​ ​a​s​s​i​s​t​ ​t​h​e​ ​i​n​t​e​r​v​i​e​w​ ​p​r​o​c​e​s​s​ ​t​h​a​t​ ​i​n​v​o​l​v​e​s​ ​t​h​e​ ​A​d​d​i​c​t​i​o​n​ ​S​e​v​e​r​i​t​y​ ​I​n​d​e​x​ ​f​o​r​m
		 */
		PARAGRAPH_1: string
		/**
		 * U​s​e​ ​t​h​e​ ​s​e​s​s​i​o​n​ ​m​e​n​u​ ​o​n​ ​t​h​e​ ​u​p​p​e​r​ ​r​i​g​h​t​ ​c​o​r​n​e​r​ ​t​o​ ​l​o​g​ ​i​n
		 */
		PARAGRAPH_2: string
		/**
		 * V​i​s​i​t​ ​t​h​e
		 */
		VISIT: string
		/**
		 * G​i​t​H​u​b​ ​r​e​p​o​s​i​t​o​r​y
		 */
		GITHUB_REPOSITORY: string
		/**
		 * t​o​ ​k​n​o​w​ ​m​o​r​e​ ​a​n​d​ ​r​e​a​d​ ​t​h​e​ ​d​o​c​u​m​e​n​t​a​t​i​o​n
		 */
		KNOW: string
	}
	settings: {
		/**
		 * L​i​b​r​e​-​A​S​I​ ​S​e​t​t​i​n​g​s
		 */
		TITLE: string
		/**
		 * L​o​c​a​l​ ​s​e​t​t​i​n​g​s​,​ ​o​n​l​y​ ​a​p​p​l​i​e​d​ ​o​n​ ​t​h​i​s​ ​b​r​o​w​s​e​r
		 */
		LOCAL_SETTINGS: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		LANGUAGE: string
		/**
		 * P​i​c​k​ ​a​ ​l​a​n​g​u​a​g​e
		 */
		PICKER: string
		/**
		 * S​e​t​t​i​n​g​s​ ​h​a​v​e​ ​b​e​e​n​ ​s​a​v​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		SUCCESS_TEXT: string
		/**
		 * T​h​e​m​e
		 */
		THEME: string
		/**
		 * P​i​c​k​ ​a​ ​t​h​e​m​e
		 */
		THEME_PICKER: string
		/**
		 * w​h​i​t​e
		 */
		WHITE: string
		/**
		 * g​1​0
		 */
		G10: string
		/**
		 * g​8​0
		 */
		G80: string
		/**
		 * g​9​0
		 */
		G90: string
		/**
		 * g​1​0​0
		 */
		G100: string
	}
	general: {
		/**
		 * S​a​v​e
		 */
		SAVE: string
		/**
		 * S​u​c​c​e​s​s
		 */
		SUCCESS: string
	}
	navMenu: {
		/**
		 * N​o​t​ ​l​o​g​g​e​d​ ​i​n
		 */
		NOT_LOGGED_IN: string
		/**
		 * L​o​g​ ​I​n
		 */
		LOGIN: string
		/**
		 * S​e​s​s​i​o​n​ ​A​c​t​i​v​e
		 */
		SESSION_ACTIVE: string
		/**
		 * S​i​g​n​ ​O​u​t
		 */
		SIGN_OUT: string
		/**
		 * W​e​l​c​o​m​e​ ​P​a​g​e
		 */
		WELCOME_PAGE: string
		/**
		 * H​o​m​e
		 */
		HOME: string
		/**
		 * M​a​n​a​g​e​m​e​n​t
		 */
		MANAGEMENT: string
		/**
		 * A​d​m​i​n​i​s​t​r​a​t​o​r​s
		 */
		ADMINISTRATORS: string
		/**
		 * I​n​t​e​r​v​i​e​w​e​r​s
		 */
		INTERVIEWERS: string
		/**
		 * L​o​a​d​i​n​g​.​.​.
		 */
		LOADING: string
	}
	cannotConnect: {
		/**
		 * E​r​r​o​r​.
		 */
		ERROR: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​w​h​i​l​e​ ​p​r​o​c​e​s​s​i​n​g​ ​y​o​u​r​ ​r​e​q​u​e​s​t​,​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r​,​ ​i​f​ ​t​h​e​ ​e​r​r​o​r​ ​p​e​r​s​i​s​t​s​.​	​C​o​n​t​a​c​t​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
		 */
		PARAGRAPH_1: string
		/**
		 * F​o​r​ ​y​o​u​r​ ​s​e​c​u​r​i​t​y​,​ ​y​o​u​r​ ​s​e​s​s​i​o​n​ ​h​a​s​ ​b​e​e​n​ ​i​n​v​a​l​i​d​a​t​e​d​.
		 */
		PARAGRAPH_2: string
		/**
		 * C​o​d​e​:​ ​5​0​3​.
		 */
		CODE: string
		/**
		 * G​o​ ​b​a​c​k​ ​t​o​ ​w​e​l​c​o​m​e​ ​p​a​g​e
		 */
		GO_BACK: string
		/**
		 * I​f​ ​y​o​u​'​r​e​ ​t​h​e​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.​.​.​ ​C​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​s​e​e​ ​s​o​m​e​ ​h​e​l​p
		 */
		IF_ADMIN: string
		/**
		 * S​t​a​t​u​s​ ​c​o​d​e​ ​5​0​3​ ​i​s​ ​t​h​r​o​w​n​ ​w​h​e​n​ ​L​i​b​r​e​-​A​S​I​ ​A​P​I​ ​r​e​f​u​s​e​d​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n​,​ ​t​h​i​s​ ​c​a​n​ ​b​e​ ​c​a​u​s​e​d​ ​b​y​
	​	​e​i​t​h​e​r​ ​m​i​s​c​o​n​f​i​g​u​r​i​n​g​ ​e​n​v​i​r​o​n​m​e​n​t​ ​v​a​r​i​a​b​l​e​s​ ​o​r​ ​s​t​o​p​p​i​n​g​ ​t​h​e​ ​A​P​I​ ​s​e​r​v​e​r​.​ ​M​a​k​e​ ​s​u​r​e​ ​i​t​ ​i​s​
	​	​r​u​n​n​i​n​g​,​ ​c​h​e​c​k​ ​s​e​r​v​e​r​ ​l​o​g​s​ ​a​n​d​ ​i​t​s​ ​a​d​d​r​e​s​s​ ​i​s​ ​c​o​r​r​e​c​t​l​y​ ​c​o​n​f​i​g​u​r​e​d​ ​o​n​ ​t​h​e​ ​s​e​r​v​e​r​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n
		 */
		HELP: string
	}
}

export type TranslationFunctions = {
	welcome: {
		/**
		 * Welcome to Libre-ASI
		 */
		TITLE: () => LocalizedString
		/**
		 * Libre-ASI is a software tool to assist the interview process that involves the Addiction Severity Index form
		 */
		PARAGRAPH_1: () => LocalizedString
		/**
		 * Use the session menu on the upper right corner to log in
		 */
		PARAGRAPH_2: () => LocalizedString
		/**
		 * Visit the
		 */
		VISIT: () => LocalizedString
		/**
		 * GitHub repository
		 */
		GITHUB_REPOSITORY: () => LocalizedString
		/**
		 * to know more and read the documentation
		 */
		KNOW: () => LocalizedString
	}
	settings: {
		/**
		 * Libre-ASI Settings
		 */
		TITLE: () => LocalizedString
		/**
		 * Local settings, only applied on this browser
		 */
		LOCAL_SETTINGS: () => LocalizedString
		/**
		 * Language
		 */
		LANGUAGE: () => LocalizedString
		/**
		 * Pick a language
		 */
		PICKER: () => LocalizedString
		/**
		 * Settings have been saved successfully
		 */
		SUCCESS_TEXT: () => LocalizedString
		/**
		 * Theme
		 */
		THEME: () => LocalizedString
		/**
		 * Pick a theme
		 */
		THEME_PICKER: () => LocalizedString
		/**
		 * white
		 */
		WHITE: () => LocalizedString
		/**
		 * g10
		 */
		G10: () => LocalizedString
		/**
		 * g80
		 */
		G80: () => LocalizedString
		/**
		 * g90
		 */
		G90: () => LocalizedString
		/**
		 * g100
		 */
		G100: () => LocalizedString
	}
	general: {
		/**
		 * Save
		 */
		SAVE: () => LocalizedString
		/**
		 * Success
		 */
		SUCCESS: () => LocalizedString
	}
	navMenu: {
		/**
		 * Not logged in
		 */
		NOT_LOGGED_IN: () => LocalizedString
		/**
		 * Log In
		 */
		LOGIN: () => LocalizedString
		/**
		 * Session Active
		 */
		SESSION_ACTIVE: () => LocalizedString
		/**
		 * Sign Out
		 */
		SIGN_OUT: () => LocalizedString
		/**
		 * Welcome Page
		 */
		WELCOME_PAGE: () => LocalizedString
		/**
		 * Home
		 */
		HOME: () => LocalizedString
		/**
		 * Management
		 */
		MANAGEMENT: () => LocalizedString
		/**
		 * Administrators
		 */
		ADMINISTRATORS: () => LocalizedString
		/**
		 * Interviewers
		 */
		INTERVIEWERS: () => LocalizedString
		/**
		 * Loading...
		 */
		LOADING: () => LocalizedString
	}
	cannotConnect: {
		/**
		 * Error.
		 */
		ERROR: () => LocalizedString
		/**
		 * Something went wrong while processing your request, try again later, if the error persists.	Contact your administrator.
		 */
		PARAGRAPH_1: () => LocalizedString
		/**
		 * For your security, your session has been invalidated.
		 */
		PARAGRAPH_2: () => LocalizedString
		/**
		 * Code: 503.
		 */
		CODE: () => LocalizedString
		/**
		 * Go back to welcome page
		 */
		GO_BACK: () => LocalizedString
		/**
		 * If you're the administrator... Click here to see some help
		 */
		IF_ADMIN: () => LocalizedString
		/**
		 * Status code 503 is thrown when Libre-ASI API refused the connection, this can be caused by
		either misconfiguring environment variables or stopping the API server. Make sure it is
		running, check server logs and its address is correctly configured on the server and try again
		 */
		HELP: () => LocalizedString
	}
}

export type Formatters = {}
