// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	welcome: {
		/**
		 * W​e​l​c​o​m​e​ ​t​o​ ​L​i​b​r​e​-​A​S​I
		 */
		TITLE: string
		/**
		 * L​i​b​r​e​-​A​S​I​ ​i​s​ ​a​ ​s​o​f​t​w​a​r​e​ ​t​o​o​l​ ​t​o​ ​a​s​s​i​s​t​ ​t​h​e​ ​i​n​t​e​r​v​i​e​w​ ​p​r​o​c​e​s​s​ ​t​h​a​t​ ​i​n​v​o​l​v​e​s​ ​t​h​e​ ​A​d​d​i​c​t​i​o​n​ ​S​e​v​e​r​i​t​y​ ​I​n​d​e​x​ ​f​o​r​m
		 */
		PARAGRAPH_1: string
		/**
		 * U​s​e​ ​t​h​e​ ​s​e​s​s​i​o​n​ ​m​e​n​u​ ​o​n​ ​t​h​e​ ​u​p​p​e​r​ ​r​i​g​h​t​ ​c​o​r​n​e​r​ ​t​o​ ​l​o​g​ ​i​n
		 */
		PARAGRAPH_2: string
		/**
		 * V​i​s​i​t​ ​t​h​e
		 */
		VISIT: string
		/**
		 * G​i​t​H​u​b​ ​r​e​p​o​s​i​t​o​r​y
		 */
		GITHUB_REPOSITORY: string
		/**
		 * t​o​ ​k​n​o​w​ ​m​o​r​e​ ​a​n​d​ ​r​e​a​d​ ​t​h​e​ ​d​o​c​u​m​e​n​t​a​t​i​o​n
		 */
		KNOW: string
	}
	settings: {
		/**
		 * L​i​b​r​e​-​A​S​I​ ​S​e​t​t​i​n​g​s
		 */
		TITLE: string
		/**
		 * L​o​c​a​l​ ​s​e​t​t​i​n​g​s​,​ ​o​n​l​y​ ​a​p​p​l​i​e​d​ ​o​n​ ​t​h​i​s​ ​b​r​o​w​s​e​r
		 */
		LOCAL_SETTINGS: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		LANGUAGE: string
		/**
		 * P​i​c​k​ ​a​ ​l​a​n​g​u​a​g​e
		 */
		PICKER: string
		/**
		 * S​e​t​t​i​n​g​s​ ​h​a​v​e​ ​b​e​e​n​ ​s​a​v​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		SUCCESS_TEXT: string
		/**
		 * T​h​e​m​e
		 */
		THEME: string
		/**
		 * P​i​c​k​ ​a​ ​t​h​e​m​e
		 */
		THEME_PICKER: string
		/**
		 * w​h​i​t​e
		 */
		WHITE: string
		/**
		 * g​1​0
		 */
		G10: string
		/**
		 * g​8​0
		 */
		G80: string
		/**
		 * g​9​0
		 */
		G90: string
		/**
		 * g​1​0​0
		 */
		G100: string
	}
	general: {
		/**
		 * S​a​v​e
		 */
		SAVE: string
		/**
		 * S​u​c​c​e​s​s
		 */
		SUCCESS: string
	}
}

export type TranslationFunctions = {
	welcome: {
		/**
		 * Welcome to Libre-ASI
		 */
		TITLE: () => LocalizedString
		/**
		 * Libre-ASI is a software tool to assist the interview process that involves the Addiction Severity Index form
		 */
		PARAGRAPH_1: () => LocalizedString
		/**
		 * Use the session menu on the upper right corner to log in
		 */
		PARAGRAPH_2: () => LocalizedString
		/**
		 * Visit the
		 */
		VISIT: () => LocalizedString
		/**
		 * GitHub repository
		 */
		GITHUB_REPOSITORY: () => LocalizedString
		/**
		 * to know more and read the documentation
		 */
		KNOW: () => LocalizedString
	}
	settings: {
		/**
		 * Libre-ASI Settings
		 */
		TITLE: () => LocalizedString
		/**
		 * Local settings, only applied on this browser
		 */
		LOCAL_SETTINGS: () => LocalizedString
		/**
		 * Language
		 */
		LANGUAGE: () => LocalizedString
		/**
		 * Pick a language
		 */
		PICKER: () => LocalizedString
		/**
		 * Settings have been saved successfully
		 */
		SUCCESS_TEXT: () => LocalizedString
		/**
		 * Theme
		 */
		THEME: () => LocalizedString
		/**
		 * Pick a theme
		 */
		THEME_PICKER: () => LocalizedString
		/**
		 * white
		 */
		WHITE: () => LocalizedString
		/**
		 * g10
		 */
		G10: () => LocalizedString
		/**
		 * g80
		 */
		G80: () => LocalizedString
		/**
		 * g90
		 */
		G90: () => LocalizedString
		/**
		 * g100
		 */
		G100: () => LocalizedString
	}
	general: {
		/**
		 * Save
		 */
		SAVE: () => LocalizedString
		/**
		 * Success
		 */
		SUCCESS: () => LocalizedString
	}
}

export type Formatters = {}
