// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAddictionSeverityIndexFormTranslation = "addiction_severity_index_form_translations"

// AddictionSeverityIndexFormTranslation mapped from table <addiction_severity_index_form_translations>
type AddictionSeverityIndexFormTranslation struct {
	ID          int16     `gorm:"column:id;primaryKey" json:"id"`
	Language    string    `gorm:"column:language;primaryKey" json:"language"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Description string    `gorm:"column:description;not null" json:"description"`
	IsDefault   bool      `gorm:"column:is_default;not null" json:"is_default"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName AddictionSeverityIndexFormTranslation's table name
func (*AddictionSeverityIndexFormTranslation) TableName() string {
	return TableNameAddictionSeverityIndexFormTranslation
}
