// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAddictionSeverityIndexForm = "addiction_severity_index_form"

// AddictionSeverityIndexForm mapped from table <addiction_severity_index_form>
type AddictionSeverityIndexForm struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Edition   string    `gorm:"column:edition;not null" json:"edition"`
	Version   int16     `gorm:"column:version;not null" json:"version"`
	Authors   string    `gorm:"column:authors;not null" json:"authors"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName AddictionSeverityIndexForm's table name
func (*AddictionSeverityIndexForm) TableName() string {
	return TableNameAddictionSeverityIndexForm
}
