// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Address   string    `gorm:"column:address;not null" json:"address"`
	City      int32     `gorm:"column:city;not null" json:"city"`
	Person    int32     `gorm:"column:person" json:"person"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	IsMain    bool      `gorm:"column:is_main;not null" json:"is_main"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
