// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAttendanceTypeTranslation = "attendance_type_translations"

// AttendanceTypeTranslation mapped from table <attendance_type_translations>
type AttendanceTypeTranslation struct {
	AttendanceType     string    `gorm:"column:attendance_type" json:"attendance_type"`
	Language           string    `gorm:"column:language;primaryKey" json:"language"`
	IsDefault          bool      `gorm:"column:is_default;not null" json:"is_default"`
	AttendanceTypeName string    `gorm:"column:attendance_type_name;primaryKey" json:"attendance_type_name"`
	CreatedAt          time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName AttendanceTypeTranslation's table name
func (*AttendanceTypeTranslation) TableName() string {
	return TableNameAttendanceTypeTranslation
}
