// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAttendant = "attendant"

// Attendant mapped from table <attendant>
type Attendant struct {
	Person    int32     `gorm:"column:person;primaryKey" json:"person"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Attendant's table name
func (*Attendant) TableName() string {
	return TableNameAttendant
}
