// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAttendanceType = "attendance_type"

// AttendanceType mapped from table <attendance_type>
type AttendanceType struct {
	AttendanceType string    `gorm:"column:attendance_type;primaryKey" json:"attendance_type"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName AttendanceType's table name
func (*AttendanceType) TableName() string {
	return TableNameAttendanceType
}
