// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameCityTranslation = "city_translations"

// CityTranslation mapped from table <city_translations>
type CityTranslation struct {
	City      int32     `gorm:"column:city;primaryKey" json:"city"`
	Language  string    `gorm:"column:language;primaryKey" json:"language"`
	IsDefault bool      `gorm:"column:is_default;not null" json:"is_default"`
	Name      string    `gorm:"column:name" json:"name"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName CityTranslation's table name
func (*CityTranslation) TableName() string {
	return TableNameCityTranslation
}
