// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameCountryTranslation = "country_translations"

// CountryTranslation mapped from table <country_translations>
type CountryTranslation struct {
	Country     string    `gorm:"column:country" json:"country"`
	Language    string    `gorm:"column:language;not null" json:"language"`
	IsDefault   bool      `gorm:"column:is_default;not null" json:"is_default"`
	CountryName string    `gorm:"column:country_name;primaryKey" json:"country_name"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName CountryTranslation's table name
func (*CountryTranslation) TableName() string {
	return TableNameCountryTranslation
}
