// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameCountry = "country"

// Country mapped from table <country>
type Country struct {
	Country    string    `gorm:"column:country;primaryKey" json:"country"`
	Region     string    `gorm:"column:region;not null" json:"region"`
	Indicative int16     `gorm:"column:indicative;not null" json:"indicative"`
	CreatedAt  time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Country's table name
func (*Country) TableName() string {
	return TableNameCountry
}
