// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDrugCategory = "drug_category"

// DrugCategory mapped from table <drug_category>
type DrugCategory struct {
	Category  string    `gorm:"column:category;primaryKey" json:"category"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName DrugCategory's table name
func (*DrugCategory) TableName() string {
	return TableNameDrugCategory
}
