// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDrug = "drug"

// Drug mapped from table <drug>
type Drug struct {
	Name      string    `gorm:"column:name;primaryKey" json:"name"`
	Category  string    `gorm:"column:category;not null" json:"category"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Drug's table name
func (*Drug) TableName() string {
	return TableNameDrug
}
