// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDrugCategoryTranslation = "drug_category_translation"

// DrugCategoryTranslation mapped from table <drug_category_translation>
type DrugCategoryTranslation struct {
	DrugCategory     string    `gorm:"column:drug_category" json:"drug_category"`
	Language         string    `gorm:"column:language;primaryKey" json:"language"`
	DrugCategoryName string    `gorm:"column:drug_category_name;primaryKey" json:"drug_category_name"`
	CreatedAt        time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName DrugCategoryTranslation's table name
func (*DrugCategoryTranslation) TableName() string {
	return TableNameDrugCategoryTranslation
}
