// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFamilyTypeTranslation = "family_type_translations"

// FamilyTypeTranslation mapped from table <family_type_translations>
type FamilyTypeTranslation struct {
	Type      string    `gorm:"column:type" json:"type"`
	Language  string    `gorm:"column:language;primaryKey" json:"language"`
	IsDefault bool      `gorm:"column:is_default;not null" json:"is_default"`
	TypeText  string    `gorm:"column:type_text;primaryKey" json:"type_text"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName FamilyTypeTranslation's table name
func (*FamilyTypeTranslation) TableName() string {
	return TableNameFamilyTypeTranslation
}
