// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFamilyType = "family_type"

// FamilyType mapped from table <family_type>
type FamilyType struct {
	Type      string    `gorm:"column:type;primaryKey" json:"type"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName FamilyType's table name
func (*FamilyType) TableName() string {
	return TableNameFamilyType
}
