// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameHollingsheadOccupationTranslation = "hollingshead_occupation_translations"

// HollingsheadOccupationTranslation mapped from table <hollingshead_occupation_translations>
type HollingsheadOccupationTranslation struct {
	Occupation     string    `gorm:"column:occupation" json:"occupation"`
	Language       string    `gorm:"column:language;primaryKey" json:"language"`
	OccupationName string    `gorm:"column:occupation_name;primaryKey" json:"occupation_name"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName HollingsheadOccupationTranslation's table name
func (*HollingsheadOccupationTranslation) TableName() string {
	return TableNameHollingsheadOccupationTranslation
}
