// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameHollingsheadOccupation = "hollingshead_occupation"

// HollingsheadOccupation mapped from table <hollingshead_occupation>
type HollingsheadOccupation struct {
	Occupation string    `gorm:"column:occupation;primaryKey" json:"occupation"`
	CreatedAt  time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName HollingsheadOccupation's table name
func (*HollingsheadOccupation) TableName() string {
	return TableNameHollingsheadOccupation
}
