// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameHousingArrangementTranslation = "housing_arrangement_translations"

// HousingArrangementTranslation mapped from table <housing_arrangement_translations>
type HousingArrangementTranslation struct {
	Type      string    `gorm:"column:type" json:"type"`
	Language  string    `gorm:"column:language;primaryKey" json:"language"`
	IsDefault bool      `gorm:"column:is_default;not null" json:"is_default"`
	TypeName  string    `gorm:"column:type_name;primaryKey" json:"type_name"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName HousingArrangementTranslation's table name
func (*HousingArrangementTranslation) TableName() string {
	return TableNameHousingArrangementTranslation
}
