// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameHousingArrangement = "housing_arrangement"

// HousingArrangement mapped from table <housing_arrangement>
type HousingArrangement struct {
	Type      string    `gorm:"column:type;primaryKey" json:"type"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName HousingArrangement's table name
func (*HousingArrangement) TableName() string {
	return TableNameHousingArrangement
}
