// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInterviewInterpretation = "interview_interpretation"

// InterviewInterpretation mapped from table <interview_interpretation>
type InterviewInterpretation struct {
	Interview      int64     `gorm:"column:interview" json:"interview"`
	Interviewer    int32     `gorm:"column:interviewer;primaryKey" json:"interviewer"`
	Interpretation string    `gorm:"column:interpretation;not null" json:"interpretation"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName InterviewInterpretation's table name
func (*InterviewInterpretation) TableName() string {
	return TableNameInterviewInterpretation
}
