// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInterviewAnswer = "interview_answer"

// InterviewAnswer mapped from table <interview_answer>
type InterviewAnswer struct {
	Interview  int64     `gorm:"column:interview;primaryKey" json:"interview"`
	Question   int64     `gorm:"column:question;not null" json:"question"`
	Language   string    `gorm:"column:language;not null" json:"language"`
	Order_     int16     `gorm:"column:order;not null" json:"order"`
	Answer     string    `gorm:"column:answer" json:"answer"`
	Commentary string    `gorm:"column:commentary" json:"commentary"`
	CreatedAt  time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName InterviewAnswer's table name
func (*InterviewAnswer) TableName() string {
	return TableNameInterviewAnswer
}
