// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInterview = "interview"

// Interview mapped from table <interview>
type Interview struct {
	ID                    int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StartDate             time.Time `gorm:"column:start_date;not null" json:"start_date"`
	EndDate               time.Time `gorm:"column:end_date" json:"end_date"`
	PausedAt              time.Time `gorm:"column:paused_at" json:"paused_at"`
	ResumedAt             time.Time `gorm:"column:resumed_at" json:"resumed_at"`
	AttendanceType        string    `gorm:"column:attendance_type;not null" json:"attendance_type"`
	CreatedAt             time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt             time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Patient               int32     `gorm:"column:patient;not null" json:"patient"`
	Interviewer           int32     `gorm:"column:interviewer;not null" json:"interviewer"`
	AsiForm               int32     `gorm:"column:asi_form;not null" json:"asi_form"`
	Language              string    `gorm:"column:language;not null" json:"language"`
	LegalSeverity         int16     `gorm:"column:legal_severity" json:"legal_severity"`
	DrugSeverity          int16     `gorm:"column:drug_severity" json:"drug_severity"`
	AlcoholSeverity       int16     `gorm:"column:alcohol_severity" json:"alcohol_severity"`
	EmploymentSeverity    int16     `gorm:"column:employment_severity" json:"employment_severity"`
	MedicalSeverity       int16     `gorm:"column:medical_severity" json:"medical_severity"`
	FamilySeverity        int16     `gorm:"column:family_severity" json:"family_severity"`
	PsychologicalSeverity int16     `gorm:"column:psychological_severity" json:"psychological_severity"`
}

// TableName Interview's table name
func (*Interview) TableName() string {
	return TableNameInterview
}
