// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInterviewReport = "interview_report"

// InterviewReport mapped from table <interview_report>
type InterviewReport struct {
	ID          int64     `gorm:"column:id;primaryKey" json:"id"`
	Interview   int64     `gorm:"column:interview;not null" json:"interview"`
	Interviewer int32     `gorm:"column:interviewer;primaryKey" json:"interviewer"`
	Text        string    `gorm:"column:text;not null" json:"text"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName InterviewReport's table name
func (*InterviewReport) TableName() string {
	return TableNameInterviewReport
}
