// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInterviewerScaleTranslation = "interviewer_scale_translations"

// InterviewerScaleTranslation mapped from table <interviewer_scale_translations>
type InterviewerScaleTranslation struct {
	Value       int16     `gorm:"column:value;primaryKey" json:"value"`
	Language    string    `gorm:"column:language;not null" json:"language"`
	IsDefault   bool      `gorm:"column:is_default;not null" json:"is_default"`
	Description string    `gorm:"column:description;not null" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName InterviewerScaleTranslation's table name
func (*InterviewerScaleTranslation) TableName() string {
	return TableNameInterviewerScaleTranslation
}
