// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInterviewAttendant = "interview_attendant"

// InterviewAttendant mapped from table <interview_attendant>
type InterviewAttendant struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Interview int64     `gorm:"column:interview;not null" json:"interview"`
	Attendant int32     `gorm:"column:attendant;not null" json:"attendant"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName InterviewAttendant's table name
func (*InterviewAttendant) TableName() string {
	return TableNameInterviewAttendant
}
