// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInterviewer = "interviewer"

// Interviewer mapped from table <interviewer>
type Interviewer struct {
	Person     int32     `gorm:"column:person;primaryKey" json:"person"`
	RMA        string    `gorm:"column:RMA;not null" json:"RMA"`
	CreatedAt  time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Profession string    `gorm:"column:profession;not null" json:"profession"`
}

// TableName Interviewer's table name
func (*Interviewer) TableName() string {
	return TableNameInterviewer
}
