// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInterviewerScale = "interviewer_scale"

// InterviewerScale mapped from table <interviewer_scale>
type InterviewerScale struct {
	Value     int16     `gorm:"column:value;primaryKey" json:"value"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName InterviewerScale's table name
func (*InterviewerScale) TableName() string {
	return TableNameInterviewerScale
}
