// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJwtBlacklist = "jwt_blacklist"

// JwtBlacklist mapped from table <jwt_blacklist>
type JwtBlacklist struct {
	Token string `gorm:"column:token;primaryKey" json:"token"`
}

// TableName JwtBlacklist's table name
func (*JwtBlacklist) TableName() string {
	return TableNameJwtBlacklist
}
