// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameMaritalStatusTranslation = "marital_status_translations"

// MaritalStatusTranslation mapped from table <marital_status_translations>
type MaritalStatusTranslation struct {
	MaritalStatus     string    `gorm:"column:marital_status" json:"marital_status"`
	Language          string    `gorm:"column:language;primaryKey" json:"language"`
	IsDefault         bool      `gorm:"column:is_default;not null" json:"is_default"`
	MaritalStatusText string    `gorm:"column:marital_status_text;primaryKey" json:"marital_status_text"`
	CreatedAt         time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName MaritalStatusTranslation's table name
func (*MaritalStatusTranslation) TableName() string {
	return TableNameMaritalStatusTranslation
}
