// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameMaritalStatus = "marital_status"

// MaritalStatus mapped from table <marital_status>
type MaritalStatus struct {
	MaritalStatus string    `gorm:"column:marital_status;primaryKey" json:"marital_status"`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName MaritalStatus's table name
func (*MaritalStatus) TableName() string {
	return TableNameMaritalStatus
}
