// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameOption = "option"

// Option mapped from table <option>
type Option struct {
	Question              int64     `gorm:"column:question;primaryKey" json:"question"`
	Language              string    `gorm:"column:language;primaryKey" json:"language"`
	Order_                int16     `gorm:"column:order;primaryKey" json:"order"`
	Description           string    `gorm:"column:description;not null" json:"description"`
	SimplifiedDescription string    `gorm:"column:simplified_description" json:"simplified_description"`
	CreatedAt             time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt             time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Option's table name
func (*Option) TableName() string {
	return TableNameOption
}
