// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePatientScaleTranslation = "patient_scale_translations"

// PatientScaleTranslation mapped from table <patient_scale_translations>
type PatientScaleTranslation struct {
	Value       int16     `gorm:"column:value;primaryKey" json:"value"`
	Language    string    `gorm:"column:language;primaryKey" json:"language"`
	IsDefault   bool      `gorm:"column:is_default;not null" json:"is_default"`
	Description string    `gorm:"column:description;not null" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName PatientScaleTranslation's table name
func (*PatientScaleTranslation) TableName() string {
	return TableNamePatientScaleTranslation
}
