// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePatientScale = "patient_scale"

// PatientScale mapped from table <patient_scale>
type PatientScale struct {
	Value     int16     `gorm:"column:value;primaryKey" json:"value"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName PatientScale's table name
func (*PatientScale) TableName() string {
	return TableNamePatientScale
}
