// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePatient = "patient"

// Patient mapped from table <patient>
type Patient struct {
	ID                   int32     `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt            time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	SocialSecurityNumber string    `gorm:"column:social_security_number" json:"social_security_number"`
	Race                 string    `gorm:"column:race" json:"race"`
	ReligiousPreference  string    `gorm:"column:religious_preference" json:"religious_preference"`
}

// TableName Patient's table name
func (*Patient) TableName() string {
	return TableNamePatient
}
