// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePerson = "person"

// Person mapped from table <person>
type Person struct {
	ID            int32     `gorm:"column:id;primaryKey" json:"id"`
	FirstName     string    `gorm:"column:first_name;not null" json:"first_name"`
	SecondName    string    `gorm:"column:second_name" json:"second_name"`
	FirstSurname  string    `gorm:"column:first_surname" json:"first_surname"`
	SecondSurname string    `gorm:"column:second_surname" json:"second_surname"`
	Age           int16     `gorm:"column:age" json:"age"`
	Birthdate     time.Time `gorm:"column:birthdate;not null" json:"birthdate"`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Person's table name
func (*Person) TableName() string {
	return TableNamePerson
}
