// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePhone = "phone"

// Phone mapped from table <phone>
type Phone struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Number    int32     `gorm:"column:number;not null" json:"number"`
	Person    int32     `gorm:"column:person;not null" json:"person"`
	Country   string    `gorm:"column:country;not null" json:"country"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Phone's table name
func (*Phone) TableName() string {
	return TableNamePhone
}
