// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameProfessionTranslation = "profession_translation"

// ProfessionTranslation mapped from table <profession_translation>
type ProfessionTranslation struct {
	Profession     string    `gorm:"column:profession" json:"profession"`
	Language       string    `gorm:"column:language;primaryKey" json:"language"`
	ProfessionName string    `gorm:"column:profession_name;primaryKey" json:"profession_name"`
	IsDefault      bool      `gorm:"column:is_default;not null" json:"is_default"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName ProfessionTranslation's table name
func (*ProfessionTranslation) TableName() string {
	return TableNameProfessionTranslation
}
