// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameProfession = "profession"

// Profession mapped from table <profession>
type Profession struct {
	Profession string    `gorm:"column:profession;primaryKey" json:"profession"`
	CreatedAt  time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Profession's table name
func (*Profession) TableName() string {
	return TableNameProfession
}
