// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameQuestionCategoryTranslation = "question_category_translations"

// QuestionCategoryTranslation mapped from table <question_category_translations>
type QuestionCategoryTranslation struct {
	Category     string    `gorm:"column:category;primaryKey" json:"category"`
	Language     string    `gorm:"column:language;primaryKey" json:"language"`
	IsDefault    bool      `gorm:"column:is_default;not null" json:"is_default"`
	CategoryName string    `gorm:"column:category_name;not null" json:"category_name"`
	Description  string    `gorm:"column:description" json:"description"`
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName QuestionCategoryTranslation's table name
func (*QuestionCategoryTranslation) TableName() string {
	return TableNameQuestionCategoryTranslation
}
