// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameQuestionHelp = "question_help"

// QuestionHelp mapped from table <question_help>
type QuestionHelp struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Question  int64     `gorm:"column:question;not null" json:"question"`
	Language  string    `gorm:"column:language;not null" json:"language"`
	Example   string    `gorm:"column:example" json:"example"`
	Help      string    `gorm:"column:help" json:"help"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName QuestionHelp's table name
func (*QuestionHelp) TableName() string {
	return TableNameQuestionHelp
}
