// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameQuestion = "question"

// Question mapped from table <question>
type Question struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Order_       int32     `gorm:"column:order;not null" json:"order"`
	Category     string    `gorm:"column:category;not null" json:"category"`
	QuestionType string    `gorm:"column:question_type;not null" json:"question_type"`
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Question's table name
func (*Question) TableName() string {
	return TableNameQuestion
}
