// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameQuestionAsiForm = "question_asi_form"

// QuestionAsiForm mapped from table <question_asi_form>
type QuestionAsiForm struct {
	AsiForm   int32     `gorm:"column:asi_form;primaryKey" json:"asi_form"`
	Question  int64     `gorm:"column:question;primaryKey" json:"question"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt string    `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName QuestionAsiForm's table name
func (*QuestionAsiForm) TableName() string {
	return TableNameQuestionAsiForm
}
