// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameQuestionTranslation = "question_translations"

// QuestionTranslation mapped from table <question_translations>
type QuestionTranslation struct {
	Question            int64     `gorm:"column:question;primaryKey" json:"question"`
	Language            string    `gorm:"column:language;primaryKey" json:"language"`
	IsDefault           bool      `gorm:"column:is_default;not null" json:"is_default"`
	Statement           string    `gorm:"column:statement;not null" json:"statement"`
	SimplifiedStatement string    `gorm:"column:simplified_statement" json:"simplified_statement"`
	CreatedAt           time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName QuestionTranslation's table name
func (*QuestionTranslation) TableName() string {
	return TableNameQuestionTranslation
}
