// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameQuestionType = "question_type"

// QuestionType mapped from table <question_type>
type QuestionType struct {
	Type      string    `gorm:"column:type;primaryKey" json:"type"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName QuestionType's table name
func (*QuestionType) TableName() string {
	return TableNameQuestionType
}
