// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameQuestionCategory = "question_category"

// QuestionCategory mapped from table <question_category>
type QuestionCategory struct {
	Category  string    `gorm:"column:category;primaryKey" json:"category"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName QuestionCategory's table name
func (*QuestionCategory) TableName() string {
	return TableNameQuestionCategory
}
