// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRaceTranslation = "race_translation"

// RaceTranslation mapped from table <race_translation>
type RaceTranslation struct {
	Race      string    `gorm:"column:race" json:"race"`
	Language  string    `gorm:"column:language;primaryKey" json:"language"`
	IsDefault bool      `gorm:"column:is_default;not null" json:"is_default"`
	RaceName  string    `gorm:"column:race_name;primaryKey" json:"race_name"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName RaceTranslation's table name
func (*RaceTranslation) TableName() string {
	return TableNameRaceTranslation
}
