// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRegionTranslation = "region_translations"

// RegionTranslation mapped from table <region_translations>
type RegionTranslation struct {
	Region     string    `gorm:"column:region;primaryKey" json:"region"`
	Language   string    `gorm:"column:language;primaryKey" json:"language"`
	IsDefault  bool      `gorm:"column:is_default;not null" json:"is_default"`
	RegionName string    `gorm:"column:region_name;not null" json:"region_name"`
	CreatedAt  time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName RegionTranslation's table name
func (*RegionTranslation) TableName() string {
	return TableNameRegionTranslation
}
