// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRegion = "region"

// Region mapped from table <region>
type Region struct {
	Region    string    `gorm:"column:region;primaryKey" json:"region"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Region's table name
func (*Region) TableName() string {
	return TableNameRegion
}
