// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameReligiousPreferenceTranslation = "religious_preference_translation"

// ReligiousPreferenceTranslation mapped from table <religious_preference_translation>
type ReligiousPreferenceTranslation struct {
	Preference            string    `gorm:"column:preference" json:"preference"`
	Language              string    `gorm:"column:language;primaryKey" json:"language"`
	PreferenceDescription string    `gorm:"column:preference_description;primaryKey" json:"preference_description"`
	IsDefault             bool      `gorm:"column:is_default;not null" json:"is_default"`
	CreatedAt             time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt             time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName ReligiousPreferenceTranslation's table name
func (*ReligiousPreferenceTranslation) TableName() string {
	return TableNameReligiousPreferenceTranslation
}
